image: docker:18.06.3-ce
services:
    - docker:18.06.3-ce-dind

before_script:
    - apk add --no-cache curl jq python py-pip
    - pip install awscli

stages:
    - build

variables:
    AWS_DEFAULT_REGION: eu-west-2
    PACKAGE_NAME: planning-poker
    REPOSITORY_URL: 624953578903.dkr.ecr.eu-west-2.amazonaws.com/davids-ecr-repository

build:
    stage: build
    script: 
        - echo "Building Docker Container"
        - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
        - docker build -t $REPOSITORY_URL/$PACKAGE_NAME .
        - docker push $REPOSITORY_URL/$PACKAGE_NAME:latest